import type { ToolDefinition } from "./types";

export const AI_TOOLS: ToolDefinition[] = [
  // ─── READ tools ────────────────────────────────────────────────
  {
    id: "search_appointments",
    name: "Search Appointments",
    description: "List and filter appointments with optional status/date filters",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "status", type: "enum", required: false, description: "Filter by status", enum: ["pending", "confirmed", "paid", "completed", "cancelled", "no_show"] },
      { name: "date", type: "string", required: false, description: "Filter by date (YYYY-MM-DD, today, tomorrow)" },
      { name: "limit", type: "number", required: false, description: "Max results (default 20)" },
    ],
    timeout: 15000,
  },
  {
    id: "get_appointment_details",
    name: "Get Appointment Details",
    description: "Get full details of a specific appointment by ID",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "appointmentId", type: "string", required: true, description: "The appointment ID" },
    ],
    timeout: 10000,
  },
  {
    id: "search_patients",
    name: "Search Patients",
    description: "Search the branch patient list",
    category: "read",
    requiredPermissions: ["patients:view"],
    requiresConfirmation: false,
    parameters: [
      { name: "query", type: "string", required: false, description: "Search term (name, phone)" },
      { name: "limit", type: "number", required: false, description: "Max results (default 20)" },
    ],
    timeout: 15000,
  },
  {
    id: "search_doctors",
    name: "Search Doctors",
    description: "Search available doctors, optionally by branch",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "query", type: "string", required: false, description: "Search term (name, specialization)" },
      { name: "branchId", type: "string", required: false, description: "Filter by branch ID" },
    ],
    timeout: 15000,
  },
  {
    id: "search_clinics",
    name: "Search Clinics",
    description: "List clinics owned by the current user",
    category: "read",
    requiredPermissions: ["clinics:manage"],
    requiresConfirmation: false,
    parameters: [
      { name: "query", type: "string", required: false, description: "Search term" },
    ],
    timeout: 15000,
  },
  {
    id: "search_branches",
    name: "Search Branches",
    description: "List branches, optionally filtered by clinic",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "clinicId", type: "string", required: false, description: "Filter by clinic ID" },
    ],
    timeout: 15000,
  },
  {
    id: "search_lab_tests",
    name: "Search Lab Tests",
    description: "Search available lab tests",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "query", type: "string", required: false, description: "Search term (test name)" },
      { name: "category", type: "string", required: false, description: "Filter by category" },
    ],
    timeout: 15000,
  },
  {
    id: "get_notifications",
    name: "Get Notifications",
    description: "List recent notifications for the user",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "unreadOnly", type: "boolean", required: false, description: "Only unread notifications" },
      { name: "limit", type: "number", required: false, description: "Max results (default 20)" },
    ],
    timeout: 10000,
  },
  {
    id: "get_subscription",
    name: "Get Subscription",
    description: "Get the current subscription status and details",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [],
    timeout: 10000,
  },
  {
    id: "get_prescriptions",
    name: "Get Prescriptions",
    description: "List prescriptions for appointments",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "appointmentId", type: "string", required: false, description: "Filter by appointment ID" },
    ],
    timeout: 10000,
  },
  {
    id: "get_lab_test_appointments",
    name: "Get Lab Test Appointments",
    description: "List lab test appointments with optional status filter",
    category: "read",
    requiredPermissions: ["lab_appointments:view"],
    requiresConfirmation: false,
    parameters: [
      { name: "status", type: "enum", required: false, description: "Filter by status", enum: ["PENDING", "APPROVED", "REJECTED", "COMPLETED", "CANCELLED"] },
      { name: "limit", type: "number", required: false, description: "Max results (default 20)" },
    ],
    timeout: 15000,
  },
  {
    id: "get_dashboard_stats",
    name: "Get Dashboard Statistics",
    description: "Get an overview of clinic performance, revenue, and appointment counts",
    category: "info",
    requiredPermissions: ["clinic:analytics", "clinic:reports"],
    requiresConfirmation: false,
    parameters: [],
    timeout: 15000,
  },
  {
    id: "get_reviews",
    name: "Get Reviews",
    description: "List patient reviews for doctors or branches",
    category: "read",
    requiredPermissions: ["reviews:view"],
    requiresConfirmation: false,
    parameters: [
      { name: "doctorId", type: "string", required: false, description: "Filter by doctor ID" },
      { name: "branchId", type: "string", required: false, description: "Filter by branch ID" },
    ],
    timeout: 10000,
  },
  {
    id: "get_staff_list",
    name: "Get Staff List",
    description: "List staff members for a branch",
    category: "read",
    requiredPermissions: ["staff:manage"],
    requiresConfirmation: false,
    parameters: [
      { name: "branchId", type: "string", required: false, description: "Branch ID (defaults to current)" },
    ],
    timeout: 10000,
  },
  {
    id: "get_branch_schedule",
    name: "Get Branch Schedule",
    description: "Get operating days and closure dates for a branch",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "branchId", type: "string", required: false, description: "Branch ID (defaults to current)" },
    ],
    timeout: 10000,
  },
  {
    id: "get_ledger",
    name: "Get Payment Ledger",
    description: "View payment ledger entries",
    category: "read",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "limit", type: "number", required: false, description: "Max results" },
    ],
    timeout: 10000,
  },
  {
    id: "get_audit_logs",
    name: "Get Audit Logs",
    description: "View AI assistant audit logs",
    category: "read",
    requiredPermissions: [],
    requiredRole: ["sys_admin"],
    requiresConfirmation: false,
    parameters: [
      { name: "limit", type: "number", required: false, description: "Max results" },
    ],
    timeout: 10000,
  },
  {
    id: "get_platform_stats",
    name: "Get Platform Statistics",
    description: "Get platform-wide statistics (super admin only)",
    category: "info",
    requiredRole: ["sys_admin"],
    requiresConfirmation: false,
    parameters: [],
    timeout: 15000,
  },
  // ─── WRITE tools (require confirmation) ───────────────────────
  {
    id: "confirm_appointment",
    name: "Confirm Appointment",
    description: "Mark a pending appointment as confirmed",
    category: "write",
    requiredPermissions: ["appointments:confirm"],
    requiresConfirmation: true,
    parameters: [
      { name: "appointmentId", type: "string", required: true, description: "The appointment ID" },
    ],
    timeout: 10000,
  },
  {
    id: "complete_appointment",
    name: "Complete Appointment",
    description: "Mark a paid appointment as completed",
    category: "write",
    requiredPermissions: ["appointments:complete"],
    requiresConfirmation: true,
    parameters: [
      { name: "appointmentId", type: "string", required: true, description: "The appointment ID" },
    ],
    timeout: 10000,
  },
  {
    id: "cancel_appointment",
    name: "Cancel Appointment",
    description: "Cancel a pending, confirmed, or paid appointment",
    category: "write",
    requiredPermissions: ["appointments:cancel"],
    requiresConfirmation: true,
    parameters: [
      { name: "appointmentId", type: "string", required: true, description: "The appointment ID" },
    ],
    timeout: 10000,
  },
  {
    id: "approve_lab_appointment",
    name: "Approve Lab Test Appointment",
    description: "Approve a pending lab test appointment",
    category: "write",
    requiredPermissions: ["lab_appointments:approve"],
    requiresConfirmation: true,
    parameters: [
      { name: "appointmentId", type: "string", required: true, description: "The lab test appointment ID" },
    ],
    timeout: 10000,
  },
  {
    id: "reject_lab_appointment",
    name: "Reject Lab Test Appointment",
    description: "Reject a pending lab test appointment",
    category: "write",
    requiredPermissions: ["lab_appointments:reject"],
    requiresConfirmation: true,
    parameters: [
      { name: "appointmentId", type: "string", required: true, description: "The lab test appointment ID" },
    ],
    timeout: 10000,
  },
  {
    id: "mark_notification_read",
    name: "Mark Notification Read",
    description: "Mark a notification as read",
    category: "write",
    requiredPermissions: [],
    requiresConfirmation: false,
    parameters: [
      { name: "notificationId", type: "string", required: true, description: "The notification ID" },
    ],
    timeout: 10000,
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return AI_TOOLS.find((t) => t.id === id);
}

export function getToolsByCategory(category: ToolDefinition["category"]): ToolDefinition[] {
  return AI_TOOLS.filter((t) => t.category === category);
}
